### ISSUE TITLE
Things to do

### ISSUE THREAD

**Issue by jaredlll08** [jaredlll08/SlimyBoyos#4]
Seeing as it is [Hacktoberfest](https://hacktoberfest.digitalocean.com/) and [Modtoberfest](https://modtoberfest.com/), here is a list of things that people could PR.

* Code optimisation
* Really anything that makes sense

**Comment by JukoiDev** [comment]
Suggestion: slimes would have low chance to spawn with items, blocks. Also when slime which picked up tnt, and then lighted or struck by lighting will explode.

**Comment by jaredlll08** [comment]
I have no plans on making the mod anything but it currently is, I just wanted slimes to pickup items, not spawn with them or do anything different depending on what item they're holding, you'll need to find another mod to do that.
